<a href="https://colab.research.google.com/github/Natalie-A/Artificial-Intelligence/blob/main/AI_ML_Group_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [992]:
import pandas as pd 
import numpy as np

121600 - Aoya Natalie 
121199 - Joy Muigai
121435 - Boaz Njeru
122846 - Terrence Brian

In [993]:
from numpy import array
from sklearn.preprocessing import Normalizer
from keras.activations import sigmoid
from keras.losses import mse
from numpy.random import uniform

Hyperparameters

In [994]:
batch_size=2
learning_rate = 0.5

Dataset

In [995]:
data={'Day 1':[30,40,50,20,15,60],'Day 2':[40,50,20,15,60,70],
 'Day 3':[50,20,15,60,70,50],'Target':[20,15,60,70,50,40]}

In [996]:
dataset=pd.DataFrame(data)

In [997]:
dataset

Day 1  Day 2  Day 3  Target
0     30     40     50      20
1     40     50     20      15
2     50     20     15      60
3     20     15     60      70
4     15     60     70      50
5     60     70     50      40

In [998]:
X=dataset.drop('Target',axis=1)
y=dataset['Target']

In [999]:
X

Day 1  Day 2  Day 3
0     30     40     50
1     40     50     20
2     50     20     15
3     20     15     60
4     15     60     70
5     60     70     50

In [1000]:
X_norm = Normalizer(norm='max').fit_transform(X)

In [1001]:
X_norm

array([[0.6       , 0.8       , 1.        ],
       [0.8       , 1.        , 0.4       ],
       [1.        , 0.4       , 0.3       ],
       [0.33333333, 0.25      , 1.        ],
       [0.21428571, 0.85714286, 1.        ],
       [0.85714286, 1.        , 0.71428571]])

In [1002]:
array(y)

array([20, 15, 60, 70, 50, 40])

In [1003]:
np.reshape(array(y),(1,-1))

array([[20, 15, 60, 70, 50, 40]])

In [1004]:
y_norm=Normalizer(norm='max').fit_transform(np.reshape(array(y),(1,-1)))

In [1005]:
y_norm

array([[0.28571429, 0.21428571, 0.85714286, 1.        , 0.71428571,
        0.57142857]])

ANN From Scratch

In [1006]:
"""weight_1=array([[.2,.1],[.3,.1],[.2,.1]])
weight_2=array([[.5],[.1]])"""

'weight_1=array([[.2,.1],[.3,.1],[.2,.1]])\nweight_2=array([[.5],[.1]])'

In [1007]:
weight_1=uniform(-1,1,(3,2)) #shape 3 by 2
weight_2=uniform(-1,1,(2,1))

In [1008]:
weight_1

array([[-0.23043904, -0.39888432],
       [-0.25984784, -0.6302111 ],
       [ 0.83481598,  0.134051  ]])

In [1009]:
weight_2

array([[ 0.51102132],
       [-0.37351994]])

In [1010]:
X_norm[0:batch_size]

array([[0.6, 0.8, 1. ],
       [0.8, 1. , 0.4]])

In [1011]:
output_1=X_norm[0:batch_size]@weight_1
output_1

array([[ 0.48867429, -0.60944847],
       [-0.11027268, -0.89569816]])

In [1012]:
act_output=sigmoid(output_1).numpy()
act_output

array([[0.61979408, 0.35218502],
       [0.47245973, 0.28993533]])

In [1013]:
pred_output=act_output@weight_2
pred_output=np.reshape(pred_output,(1,-1))

Mean Squared Error

In [1014]:
y_true=y_norm[0][0:batch_size]
y_pred=pred_output
y_pred

array([[0.18517986, 0.13314037]])

In [1015]:
y_true

array([0.28571429, 0.21428571])

In [1016]:
mse(y_true,y_pred).numpy()

array([0.00834587])

Back Propagation

step 1. use the pred_output to calculate the error at node k using the first value of each array

step 2. calculate error at node j

step 3. calculate the error at node i

step 4. use these errors to update the weights

In [1017]:
for i in range(100):
  multiplication_side = y_pred*(1-y_pred)
  error_k = y_true-y_pred*multiplication_side

  out_j = act_output[0][0]
  mult_side = out_j*(1-out_j)
  error_j = error_k*weight_2[0]* mult_side

  out_i = act_output[0][1]
  mult_side_2 = out_i*(1-out_i)
  error_i = error_k*weight_2[0]* mult_side_2

  delta_k = learning_rate * error_k * y_pred
  delta_j = learning_rate * error_j * act_output[0][0]
  delta_i = learning_rate * error_i * act_output[0][1]

  new_jk = weight_2[0][0] + delta_k
  new_ik = weight_2[1][0] + delta_k

  new_1j = weight_1[0][0] + delta_j
  new_2j = weight_1[1][0] + delta_j
  new_3j = weight_1[2][0] + delta_j

  new_1i = weight_1[0][1] + delta_i
  new_2i = weight_1[1][1] + delta_i
  new_3i = weight_1[2][1] + delta_i

  weight_1 = array ([[new_1j[0][0],new_1i[0][0]],
             [new_2j[0][0],new_2i[0][0]],
              [new_3j[0][0],new_3i[0][0]]])
  weight_2 = array([[new_jk[0][0]],[new_ik[0][0]]])

In [1018]:
weight_2

array([[2.89773798],
       [2.01319672]])

In [1019]:
weight_1

array([[2.95548693, 1.35384439],
       [2.92607813, 1.12251762],
       [4.02074195, 1.88677972]])